### ISSUE TITLE
When trying to make a new invoice, the new one isnt saved and are not showing in the list

### ISSUE THREAD

**Issue by solinco** [mamont77/faktura#7]

**Comment by mamont77** [comment]
I can reproduce it on http://virt.solinco.dk/solinco/faktura/index.php?indhold=invoice&side=rediger. In process.

**Comment by mamont77** [comment]
Fixed in inc/kon_invoice_new.php on http://virt.solinco.dk/solinco/faktura/index.php?indhold=invoice&side=oversigt.

The result:

![solinco v 1 75 - google chrome 07-13-2015 16 01 47](https://cloud.githubusercontent.com/assets/970967/8650114/0819c21a-2979-11e5-857e-5cbb83ea9a65.png)

Please review and deploy the file to PROD.

**Comment by solinco** [comment]
Resolved :-)
